/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.JOptionPane;

import controller.*;
import models.Bill;
import view.userDashboardLoggedIn;

/**
 *
 * @author acer
 */
public class advPayement extends javax.swing.JFrame {

    /**
     * Creates new form advPayement
     */
    public advPayement() {
        initComponents();
       view();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        datetf = new javax.swing.JTextField();
        nametf = new javax.swing.JTextField();
        totaltf = new javax.swing.JTextField();
        paidtf = new javax.swing.JTextField();
        remainigtf = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Full Name : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setText("Total Amount :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel3.setText("Paid Amount : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel4.setText("Remaining Amount :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel5.setText("Date : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        getContentPane().add(datetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 170, -1));

        nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametfActionPerformed(evt);
            }
        });
        getContentPane().add(nametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 160, -1));
        getContentPane().add(totaltf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 140, -1));

        paidtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                paidtfFocusLost(evt);
            }
        });
        paidtf.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                paidtfInputMethodTextChanged(evt);
            }
        });
        paidtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidtfActionPerformed(evt);
            }
        });
        getContentPane().add(paidtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 150, -1));
        getContentPane().add(remainigtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 110, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(102, 102, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("KARYAKRAM ADVANCE PAYEMENT");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 80));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String email = null;

        int total = Integer.parseInt(totaltf.getText());
        int paid = Integer.parseInt(paidtf.getText());
        int remaining = Integer.parseInt(remainigtf.getText());
        String date = datetf.getText();
        try{
            ResultSet rs = new UserController().selectEmail();
            while(rs.next()){
                email = rs.getString(1);
            }
            Bill b = new Bill(0,email,total,paid,remaining,date,null);
            BillController bc = new BillController();
            // b.setName(name);
            int result = bc.insertDetails(b);
            if(result>0){
                JOptionPane.showMessageDialog(this,"Sucessfully Paid");
                dispose();
    new userDashboardLoggedIn().setVisible(true);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    // JOptionPane.showMessageDialog(this,"Sucessfully Paid");

    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void paidtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paidtfActionPerformed

    private void paidtfInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_paidtfInputMethodTextChanged
        // TODO add your handling code here:
        remaining();
    }//GEN-LAST:event_paidtfInputMethodTextChanged

    private void paidtfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paidtfFocusLost
      remaining();
    }//GEN-LAST:event_paidtfFocusLost
    public void view(){
        try{
        String name = null;
        String date = null;
        String total = null;


        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
   LocalDateTime now = LocalDateTime.now();
   date = dtf.format(now);
        // ResultSet isInserted = bc.display();
        ResultSet userRs = new UserController().selectName();
        while(userRs.next()){
            name = userRs.getString(1);
        }
        ResultSet bookingRs = new bookingController().selectTotal();
        while(bookingRs.next()){
            total = bookingRs.getString(1);
        }
        ResultSet rs = new BillController().selectDetails();
        while(rs.next()){
            int paid =Integer.parseInt(rs.getString(1));
            total = Integer.toString(Integer.parseInt(total) - paid);

        }
        nametf.setText(name);
        datetf.setText(date);
        totaltf.setText(total);



        
       

    }
    catch (Exception e){
        e.printStackTrace();
    }
}

public void remaining(){
    int total = Integer.parseInt(totaltf.getText());
    int paid = Integer.parseInt(paidtf.getText());
    int remaining = total - paid;
    remainigtf.setText(String.valueOf(remaining));
}

    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(advPayement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(advPayement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(advPayement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(advPayement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new advPayement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField datetf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nametf;
    private javax.swing.JTextField paidtf;
    private javax.swing.JTextField remainigtf;
    private javax.swing.JTextField totaltf;
    // End of variables declaration//GEN-END:variables
}
