/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author DELL
 */
public class Contact extends javax.swing.JFrame {

    /**
     * Creates new form Contact
     */
    public Contact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        karyakram1 = new javax.swing.JButton();
        karyakram2 = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        karyakram = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        navigation_bar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagespath/karayakam.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, -1));

        karyakram1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        karyakram1.setText("Karyakam");
        karyakram1.setBorder(null);
        karyakram1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                karyakram1FocusGained(evt);
            }
        });
        karyakram1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyakram1ActionPerformed(evt);
            }
        });
        jPanel1.add(karyakram1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 130, 40));

        karyakram2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        karyakram2.setText("Services");
        karyakram2.setBorder(null);
        karyakram2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                karyakram2FocusGained(evt);
            }
        });
        karyakram2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyakram2ActionPerformed(evt);
            }
        });
        jPanel1.add(karyakram2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 130, 40));

        home_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        home_btn.setText("What we do");
        home_btn.setBorder(null);
        home_btn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                home_btnFocusGained(evt);
            }
        });
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        jPanel1.add(home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 160, 40));

        karyakram.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        karyakram.setText("Resources");
        karyakram.setBorder(null);
        karyakram.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                karyakramFocusGained(evt);
            }
        });
        karyakram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyakramActionPerformed(evt);
            }
        });
        jPanel1.add(karyakram, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 130, 40));

        jButton6.setBackground(new java.awt.Color(242, 242, 242));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 102, 255));
        jButton6.setText("Register");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 20, 150, 50));

        navigation_bar.setBackground(new java.awt.Color(255, 255, 255));
        navigation_bar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(navigation_bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 113));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Group 28.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 28)); // NOI18N
        jLabel2.setText("CONTACT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void karyakram1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_karyakram1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_karyakram1FocusGained

    private void karyakram1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyakram1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_karyakram1ActionPerformed

    private void karyakram2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_karyakram2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_karyakram2FocusGained

    private void karyakram2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyakram2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_karyakram2ActionPerformed

    private void home_btnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_home_btnFocusGained
        // TODO add your handling code here:
        // home_btn.setSize(getPreferredSize());

    }//GEN-LAST:event_home_btnFocusGained

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_home_btnActionPerformed

    private void karyakramFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_karyakramFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_karyakramFocusGained

    private void karyakramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyakramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_karyakramActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new Register().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home_btn;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton karyakram;
    private javax.swing.JButton karyakram1;
    private javax.swing.JButton karyakram2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel navigation_bar;
    // End of variables declaration//GEN-END:variables
}
