/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Sandeep
 */
public class Hire extends javax.swing.JFrame {

  /**
   * Creates new form Hire
   */
  public Hire() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    Hire = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jCheckBox1 = new javax.swing.JCheckBox();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jPanel5 = new javax.swing.JPanel();
    jCheckBox2 = new javax.swing.JCheckBox();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    jCheckBox3 = new javax.swing.JCheckBox();
    jLabel14 = new javax.swing.JLabel();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jScrollBar1 = new javax.swing.JScrollBar();
    jButton5 = new javax.swing.JButton();
    jLabel17 = new javax.swing.JLabel();
    jPanel6 = new javax.swing.JPanel();
    jCheckBox4 = new javax.swing.JCheckBox();
    jLabel18 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    jPanel7 = new javax.swing.JPanel();
    jCheckBox5 = new javax.swing.JCheckBox();
    jLabel22 = new javax.swing.JLabel();
    jLabel23 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jCheckBox6 = new javax.swing.JCheckBox();
    jLabel5 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel20 = new javax.swing.JLabel();
    jPanel8 = new javax.swing.JPanel();
    jCheckBox7 = new javax.swing.JCheckBox();
    jLabel13 = new javax.swing.JLabel();
    jLabel24 = new javax.swing.JLabel();
    jPanel9 = new javax.swing.JPanel();
    jCheckBox8 = new javax.swing.JCheckBox();
    jLabel25 = new javax.swing.JLabel();
    jLabel26 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    Hire.setPreferredSize(new java.awt.Dimension(1366, 786));
    Hire.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel2.setBackground(new java.awt.Color(252, 252, 252));
    jPanel2.setBorder(
      javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))
    );
    jPanel2.setPreferredSize(new java.awt.Dimension(1366, 113));

    jLabel1.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/view/karyakram logo.png")
      )
    ); // NOI18N
    jLabel1.setText("jLabel1");

    jButton1.setBackground(new java.awt.Color(242, 242, 242));
    jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    jButton1.setText("Karyakram");
    jButton1.setBorder(null);
    jButton1.setBorderPainted(false);
    jButton1.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton1ActionPerformed(evt);
        }
      }
    );

    jButton2.setBackground(new java.awt.Color(242, 242, 242));
    jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    jButton2.setText("What we do");
    jButton2.setBorder(null);
    jButton2.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton2ActionPerformed(evt);
        }
      }
    );

    jButton3.setBackground(new java.awt.Color(242, 242, 242));
    jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    jButton3.setText("Service");
    jButton3.setBorder(null);

    jButton4.setBackground(new java.awt.Color(242, 242, 242));
    jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    jButton4.setText("Resources");
    jButton4.setBorder(null);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
      jPanel2
    );
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel2Layout
            .createSequentialGroup()
            .addComponent(
              jLabel1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              345,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(97, 97, 97)
            .addComponent(jButton1)
            .addGap(99, 99, 99)
            .addComponent(jButton2)
            .addGap(105, 105, 105)
            .addComponent(jButton3)
            .addGap(107, 107, 107)
            .addComponent(jButton4)
            .addGap(0, 191, Short.MAX_VALUE)
        )
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel2Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(
              jLabel1,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addComponent(jButton1)
            .addComponent(jButton2)
            .addComponent(jButton3)
            .addComponent(jButton4)
        )
    );

    Hire.add(
      jPanel2,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1)
    );

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
    jLabel2.setText("What personals");
    Hire.add(
      jLabel2,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 131, 361, -1)
    );

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
    jLabel3.setText("do you want to ");
    Hire.add(
      jLabel3,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 201, 282, -1)
    );

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
    jLabel4.setText("HIRE??");
    Hire.add(
      jLabel4,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 255, -1, -1)
    );

    jPanel3.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
    jCheckBox1.setText("Shreejan Manadhar");

    jLabel6.setText("5 years experience");

    jLabel7.setText("Official Events Expert");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
      jPanel3
    );
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel3Layout
            .createSequentialGroup()
            .addGap(15, 15, 15)
            .addGroup(
              jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jLabel7,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  126,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(jLabel6)
                .addComponent(
                  jCheckBox1,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  147,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addContainerGap(102, Short.MAX_VALUE)
        )
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel3Layout
            .createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(jCheckBox1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel7)
            .addContainerGap(50, Short.MAX_VALUE)
        )
    );

    Hire.add(
      jPanel3,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 333, -1, -1)
    );

    jPanel5.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jCheckBox2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
    jCheckBox2.setText("Prashant Basel");

    jLabel9.setText("5 years experience");

    jLabel10.setText("Wedding/Birthday expert");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
      jPanel5
    );
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
      jPanel5Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel5Layout
            .createSequentialGroup()
            .addGroup(
              jPanel5Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel5Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                      jCheckBox2,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      119,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  jPanel5Layout
                    .createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addGroup(
                      jPanel5Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addComponent(
                          jLabel10,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          147,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addComponent(
                          jLabel9,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          119,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                )
            )
            .addContainerGap(121, Short.MAX_VALUE)
        )
    );
    jPanel5Layout.setVerticalGroup(
      jPanel5Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel5Layout
            .createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jCheckBox2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel9)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel10)
            .addContainerGap(55, Short.MAX_VALUE)
        )
    );

    Hire.add(
      jPanel5,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 333, 290, -1)
    );

    jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel11.setText("Event Manager");
    Hire.add(
      jLabel11,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 302, 295, -1)
    );

    jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel12.setText("DECORATER");
    Hire.add(
      jLabel12,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 916, -1, -1)
    );

    jPanel4.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
    jCheckBox3.setText("Shrawani KC");
    jCheckBox3.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jCheckBox3ActionPerformed(evt);
        }
      }
    );

    jLabel14.setText("4 years experience");

    jLabel15.setText("All round expertise");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
      jPanel4
    );
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  jCheckBox3,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  113,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(
                  jLabel14,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  116,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(jLabel15)
            )
            .addContainerGap(142, Short.MAX_VALUE)
        )
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel4Layout
            .createSequentialGroup()
            .addGap(29, 29, 29)
            .addComponent(jCheckBox3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel14)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel15)
            .addContainerGap(57, Short.MAX_VALUE)
        )
    );

    Hire.add(
      jPanel4,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 527, -1, -1)
    );

    jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel16.setText("Security Mananger");
    Hire.add(
      jLabel16,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 180, -1)
    );
    Hire.add(
      jScrollBar1,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(1342, 120, -1, 668)
    );

    jButton5.setBackground(new java.awt.Color(102, 102, 255));
    jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jButton5.setForeground(new java.awt.Color(255, 255, 255));
    jButton5.setText("HIRE");
    jButton5.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton5ActionPerformed(evt);
        }
      }
    );
    Hire.add(
      jButton5,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 720, 129, 51)
    );

    jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel17.setText("Event Cordinator");
    Hire.add(
      jLabel17,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 302, -1, -1)
    );

    jPanel6.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jCheckBox4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
    jCheckBox4.setText("Abhigya Shrestha");

    jLabel18.setText("3 years experience");

    jLabel19.setText("All round experience");

    jLabel21.setText("ALl round expert");

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
      jPanel6
    );
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
      jPanel6Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          jPanel6Layout
            .createSequentialGroup()
            .addContainerGap(12, Short.MAX_VALUE)
            .addGroup(
              jPanel6Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel6Layout
                    .createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(
                      jLabel19,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      123,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  jPanel6Layout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.TRAILING
                    )
                    .addComponent(
                      jCheckBox4,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      131,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addComponent(
                      jLabel18,
                      javax.swing.GroupLayout.Alignment.LEADING,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      107,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addComponent(
                      jLabel21,
                      javax.swing.GroupLayout.Alignment.LEADING,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      101,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addContainerGap()
        )
    );
    jPanel6Layout.setVerticalGroup(
      jPanel6Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel6Layout
            .createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(jCheckBox4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel18)
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(jLabel21)
            .addGap(114, 114, 114)
            .addComponent(jLabel19)
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    Hire.add(
      jPanel6,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 260, 150)
    );

    jPanel7.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jCheckBox5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
    jCheckBox5.setText("Parash Hamal");

    jLabel22.setText("4 years experience");

    jLabel23.setText("Official event expert");

    javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
      jPanel7
    );
    jPanel7.setLayout(jPanel7Layout);
    jPanel7Layout.setHorizontalGroup(
      jPanel7Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel7Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel7Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel7Layout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.TRAILING
                    )
                    .addComponent(
                      jLabel22,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      108,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addComponent(
                      jCheckBox5,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      121,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
                .addGroup(
                  jPanel7Layout
                    .createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(
                      jLabel23,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      114,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                )
            )
            .addContainerGap(131, Short.MAX_VALUE)
        )
    );
    jPanel7Layout.setVerticalGroup(
      jPanel7Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel7Layout
            .createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jCheckBox5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel22)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel23)
            .addContainerGap(56, Short.MAX_VALUE)
        )
    );

    Hire.add(
      jPanel7,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 340, 270, 150)
    );

    jPanel1.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jCheckBox6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
    jCheckBox6.setText("Slesha Dahal");

    jLabel5.setText("6 years experience");

    jLabel8.setText("All round experience");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel1Layout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.LEADING,
                      false
                    )
                    .addComponent(
                      jCheckBox6,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(
                      jLabel5,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      118,
                      Short.MAX_VALUE
                    )
                )
                .addComponent(jLabel8)
            )
            .addContainerGap(160, Short.MAX_VALUE)
        )
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(jCheckBox6)
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel8)
            .addContainerGap(53, Short.MAX_VALUE)
        )
    );

    Hire.add(
      jPanel1,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 290, 160)
    );

    jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel20.setText("Decorater");
    Hire.add(
      jLabel20,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 496, 180, -1)
    );

    jPanel8.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jCheckBox7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
    jCheckBox7.setText("Aryan Jung Karki");

    jLabel13.setText("7 years experience");

    jLabel24.setText("Expert security guards");

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(
      jPanel8
    );
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
      jPanel8Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel8Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel8Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel8Layout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.LEADING,
                      false
                    )
                    .addComponent(
                      jCheckBox7,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(
                      jLabel13,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                )
                .addComponent(jLabel24)
            )
            .addContainerGap(166, Short.MAX_VALUE)
        )
    );
    jPanel8Layout.setVerticalGroup(
      jPanel8Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel8Layout
            .createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(jCheckBox7)
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(jLabel13)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel24)
            .addContainerGap(59, Short.MAX_VALUE)
        )
    );

    Hire.add(
      jPanel8,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, -1, -1)
    );

    jPanel9.setBorder(
      new javax.swing.border.SoftBevelBorder(
        javax.swing.border.BevelBorder.RAISED
      )
    );

    jCheckBox8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
    jCheckBox8.setText("Ramesh Maharjan");

    jLabel25.setText("3 years experience");

    jLabel26.setText("Expert security guards");

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(
      jPanel9
    );
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
      jPanel9Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel9Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel9Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  jPanel9Layout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.LEADING,
                      false
                    )
                    .addComponent(
                      jCheckBox8,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(
                      jLabel25,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                )
                .addComponent(jLabel26)
            )
            .addContainerGap(160, Short.MAX_VALUE)
        )
    );
    jPanel9Layout.setVerticalGroup(
      jPanel9Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel9Layout
            .createSequentialGroup()
            .addGap(25, 25, 25)
            .addComponent(jCheckBox8)
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(jLabel25)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel26)
            .addContainerGap(53, Short.MAX_VALUE)
        )
    );

    Hire.add(
      jPanel9,
      new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 530, -1, 160)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addComponent(
              Hire,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(0, 0, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap()
            .addComponent(
              Hire,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_jButton2ActionPerformed

  private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jCheckBox3ActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_jCheckBox3ActionPerformed

  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton5ActionPerformed
    new advPayement().setVisible(true);
    // TODO add your handling code here:

  } //GEN-LAST:event_jButton5ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(Hire.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(Hire.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(Hire.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(Hire.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new Hire().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel Hire;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JCheckBox jCheckBox2;
  private javax.swing.JCheckBox jCheckBox3;
  private javax.swing.JCheckBox jCheckBox4;
  private javax.swing.JCheckBox jCheckBox5;
  private javax.swing.JCheckBox jCheckBox6;
  private javax.swing.JCheckBox jCheckBox7;
  private javax.swing.JCheckBox jCheckBox8;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel20;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel22;
  private javax.swing.JLabel jLabel23;
  private javax.swing.JLabel jLabel24;
  private javax.swing.JLabel jLabel25;
  private javax.swing.JLabel jLabel26;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JPanel jPanel8;
  private javax.swing.JPanel jPanel9;
  private javax.swing.JScrollBar jScrollBar1;
  // End of variables declaration//GEN-END:variables
}
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Sandeep
 */
public class Hire extends javax.swing.JFrame {

    /**
     * Creates new form Hire
     */
    public Hire() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hire = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Hire.setPreferredSize(new java.awt.Dimension(1366, 786));
        Hire.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 113));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/karyakram logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Karyakram");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("What we do");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("Service");
        jButton3.setBorder(null);

        jButton4.setBackground(new java.awt.Color(242, 242, 242));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setText("Resources");
        jButton4.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jButton1)
                .addGap(99, 99, 99)
                .addComponent(jButton2)
                .addGap(105, 105, 105)
                .addComponent(jButton3)
                .addGap(107, 107, 107)
                .addComponent(jButton4)
                .addGap(0, 191, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addComponent(jButton2)
                .addComponent(jButton3)
                .addComponent(jButton4))
        );

        Hire.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("What personals");
        Hire.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 131, 361, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("do you want to ");
        Hire.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 201, 282, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("HIRE??");
        Hire.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 255, -1, -1));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jCheckBox1.setText("Shreejan Manadhar");

        jLabel6.setText("5 years experience");

        jLabel7.setText("Official Events Expert");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        Hire.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 333, -1, -1));

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jCheckBox2.setText("Prashant Basel");

        jLabel9.setText("5 years experience");

        jLabel10.setText("Wedding/Birthday expert");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        Hire.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 333, 290, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Event Manager");
        Hire.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 302, 295, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("DECORATER");
        Hire.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 916, -1, -1));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jCheckBox3.setText("Shrawani KC");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jLabel14.setText("4 years experience");

        jLabel15.setText("All round expertise");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        Hire.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 527, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Security Mananger");
        Hire.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 180, -1));
        Hire.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1342, 120, -1, 668));

        jButton5.setBackground(new java.awt.Color(102, 102, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("HIRE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Hire.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 720, 129, 51));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Event Cordinator");
        Hire.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 302, -1, -1));

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jCheckBox4.setText("Abhigya Shrestha");

        jLabel18.setText("3 years experience");

        jLabel19.setText("All round experience");

        jLabel21.setText("ALl round expert");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addGap(114, 114, 114)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Hire.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 260, 150));

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jCheckBox5.setText("Parash Hamal");

        jLabel22.setText("4 years experience");

        jLabel23.setText("Official event expert");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        Hire.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 340, 270, 150));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jCheckBox6.setText("Slesha Dahal");

        jLabel5.setText("6 years experience");

        jLabel8.setText("All round experience");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                    .addComponent(jLabel8))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        Hire.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 290, 160));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Decorater");
        Hire.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 496, 180, -1));

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jCheckBox7.setText("Aryan Jung Karki");

        jLabel13.setText("7 years experience");

        jLabel24.setText("Expert security guards");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBox7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel24))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        Hire.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 530, -1, -1));

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCheckBox8.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jCheckBox8.setText("Ramesh Maharjan");

        jLabel25.setText("3 years experience");

        jLabel26.setText("Expert security guards");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCheckBox8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel26))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        Hire.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 530, -1, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Hire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
new advPayement().setVisible(true);
           // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Hire;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
