/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UserController;
import javax.swing.JOptionPane;
import models.User;

/**
 *
 * @author Sandeep
 */
public class Register extends javax.swing.JFrame {

  /**
   * Creates new form Register
   */
  public Register() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jButton1 = new javax.swing.JButton();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    fText = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    lText = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    eText = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    cText = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jButton2 = new javax.swing.JButton();
    rpText = new javax.swing.JPasswordField();
    pText = new javax.swing.JPasswordField();

    jButton1.setBackground(new java.awt.Color(102, 102, 255));
    jButton1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 12)); // NOI18N
    jButton1.setText("Register");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setForeground(new java.awt.Color(204, 204, 204));

    jLabel1.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(102, 102, 255));
    jLabel1.setText("Register");

    jLabel2.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
    jLabel2.setText("First name");

    fText.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          fTextActionPerformed(evt);
        }
      }
    );

    jLabel3.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
    jLabel3.setText("Surname");

    lText.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          lTextActionPerformed(evt);
        }
      }
    );

    jLabel4.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
    jLabel4.setText("Email");

    jLabel5.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
    jLabel5.setText("Phone number");

    jLabel6.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
    jLabel6.setText("Password");

    jLabel7.setFont(new java.awt.Font("Swis721 WGL4 BT", 0, 12)); // NOI18N
    jLabel7.setText("Confirm Password");

    jButton2.setBackground(new java.awt.Color(102, 102, 255));
    jButton2.setFont(new java.awt.Font("Swis721 WGL4 BT", 1, 12)); // NOI18N
    jButton2.setForeground(new java.awt.Color(255, 255, 255));
    jButton2.setText("Register");
    jButton2.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          jButton2ActionPerformed(evt);
        }
      }
    );

    rpText.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          rpTextActionPerformed(evt);
        }
      }
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
      jPanel1
    );
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addContainerGap()
            .addGroup(
              jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rpText)
                .addComponent(pText)
                .addGroup(
                  jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                      jPanel1Layout
                        .createParallelGroup(
                          javax.swing.GroupLayout.Alignment.LEADING
                        )
                        .addGroup(
                          javax.swing.GroupLayout.Alignment.TRAILING,
                          jPanel1Layout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING
                            )
                            .addGroup(
                              jPanel1Layout
                                .createParallelGroup(
                                  javax.swing.GroupLayout.Alignment.TRAILING,
                                  false
                                )
                                .addComponent(cText)
                                .addComponent(eText)
                                .addComponent(
                                  jLabel2,
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  79,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(
                                  jLabel1,
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  108,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(
                                  jLabel3,
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  60,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(
                                  jLabel4,
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  77,
                                  javax.swing.GroupLayout.PREFERRED_SIZE
                                )
                                .addComponent(
                                  fText,
                                  javax.swing.GroupLayout.Alignment.LEADING,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  321,
                                  Short.MAX_VALUE
                                )
                                .addComponent(
                                  lText,
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                                .addComponent(
                                  jLabel5,
                                  javax.swing.GroupLayout.Alignment.LEADING
                                )
                            )
                            .addComponent(jLabel6)
                        )
                        .addComponent(
                          jLabel7,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          111,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                    )
                    .addGap(0, 0, Short.MAX_VALUE)
                )
            )
            .addGap(22, 22, 22)
        )
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addGap(109, 109, 109)
            .addComponent(
              jButton2,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              107,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(133, Short.MAX_VALUE)
        )
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          jPanel1Layout
            .createSequentialGroup()
            .addGap(14, 14, 14)
            .addComponent(jLabel1)
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              fText,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              31,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              lText,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              31,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              eText,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              31,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              cText,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              37,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              pText,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              31,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              rpText,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              31,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              20,
              Short.MAX_VALUE
            )
            .addComponent(
              jButton2,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              42,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap()
        )
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(157, 157, 157)
            .addComponent(
              jPanel1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(238, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addComponent(
              jPanel1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(0, 0, Short.MAX_VALUE)
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void fTextActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_fTextActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_fTextActionPerformed

  private void lTextActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_lTextActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_lTextActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    String fname = fText.getText();
    String lname = lText.getText();
    String email = eText.getText();
    String phone = cText.getText();
    String pass = new String(pText.getPassword());
    String repass = new String(rpText.getPassword());
    if (
      fname.equals("") ||
      lname.equals("") ||
      email.equals("") ||
      phone.equals("") ||
      pass.equals("") ||
      repass.equals("")
    ) {
      JOptionPane.showMessageDialog(null, " Please enter all  the details");
    } else if (!pass.equals(repass)) {
      JOptionPane.showMessageDialog(
        null,
        " Please enter same password and confirm password"
      );
    } else {
      try {
        User u1 = new User(
          fText.getText(),
          lText.getText(),
          eText.getText(),
          cText.getText(),
          new String(pText.getPassword()
          sText.getText(),)
        );
        UserController uc = new UserController();
        int result = uc.insertDetails(u1);
        if (result > 0) {
          JOptionPane.showMessageDialog(null, " Register Success");
        } else {
          JOptionPane.showMessageDialog(null, "Not successful");
        }
      } catch (Exception e) {
        // TODO: handle exception
        JOptionPane.showMessageDialog(null, e);
      }
    }
  } //GEN-LAST:event_jButton2ActionPerformed

  private void rpTextActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_rpTextActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_rpTextActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(Register.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(Register.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(Register.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(Register.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          new Register().setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField cText;
  private javax.swing.JTextField eText;
  private javax.swing.JTextField fText;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField lText;
  private javax.swing.JPasswordField pText;
  private javax.swing.JPasswordField rpText;
  // End of variables declaration//GEN-END:variables
}
